// Frontend type definitions mirroring @synth-deploy/core types.
// Dates come as ISO strings from the API.

// Re-export approval constants directly from core source (only imports zod, safe for browser).
export { DEFAULT_APPROVAL_DEFAULTS } from "../../core/src/types.js";

export type ApprovalMode = "auto" | "required";

export interface ApprovalDefaults {
  query: ApprovalMode;
  investigate: ApprovalMode;
  trigger: ApprovalMode;
  deploy: ApprovalMode;
  maintain: ApprovalMode;
  execute: ApprovalMode;
  composite: ApprovalMode;
  environmentOverrides: Record<string, Partial<Record<string, ApprovalMode>>>;
}

export type ConflictPolicy = "strict" | "permissive";

export type TaskModelTask =
  | "logClassification"
  | "diagnosticSynthesis"
  | "postmortemGeneration"
  | "queryAnswering";

export interface TaskModelConfig {
  logClassification?: string;
  diagnosticSynthesis?: string;
  postmortemGeneration?: string;
  queryAnswering?: string;
}

export interface TaskModelMeta {
  label: string;
  tier: string;
  tokenBudget: string;
  reasoningDepth: string;
}

export const TASK_MODEL_META: Record<TaskModelTask, TaskModelMeta> = {
  logClassification: {
    label: "Log pattern classification",
    tier: "Lightweight",
    tokenBudget: "~1,024",
    reasoningDepth: "Structured classification",
  },
  diagnosticSynthesis: {
    label: "Diagnostic report synthesis",
    tier: "Mid-range",
    tokenBudget: "~2,048",
    reasoningDepth: "Evidence \u2192 narrative",
  },
  postmortemGeneration: {
    label: "Postmortem generation",
    tier: "Capable",
    tokenBudget: "~4,096",
    reasoningDepth: "Multi-event causal chain",
  },
  queryAnswering: {
    label: "Query answering",
    tier: "Mid-range",
    tokenBudget: "~1,024",
    reasoningDepth: "Data-grounded synthesis",
  },
};

export interface CapabilityVerificationResult {
  task: string;
  model: string;
  status: "verified" | "marginal" | "insufficient";
  explanation: string;
}

export type LlmEntityExposure = "names" | "none";

export interface AgentSettings {
  defaultHealthCheckRetries: number;
  defaultTimeoutMs: number;
  conflictPolicy: ConflictPolicy;
  defaultVerificationStrategy: "basic" | "full" | "none";
  llmEntityExposure?: LlmEntityExposure;
  taskModels?: TaskModelConfig;
}

export interface DeploymentDefaults {
  defaultHealthCheckEnabled: boolean;
  defaultHealthCheckRetries: number;
  defaultTimeoutMs: number;
  defaultVerificationStrategy: "basic" | "full" | "none";
}

export interface EnvoyEndpointConfig {
  url: string;
  timeoutMs: number;
}

export interface CoBrandingConfig {
  operatorName: string;
  logoUrl: string;
  accentColor?: string;
}

export interface McpServerConfig {
  name: string;
  url: string;
  description?: string;
}

export type LlmProvider = "claude" | "openai" | "gemini" | "grok" | "deepseek" | "ollama" | "custom";

export interface LlmFallbackConfig {
  provider: LlmProvider;
  apiKeyConfigured: boolean;
  baseUrl?: string;
  model: string;
  timeoutMs: number;
}

export interface LlmProviderConfig {
  provider: LlmProvider;
  apiKeyConfigured: boolean;
  baseUrl?: string;
  reasoningModel: string;
  classificationModel: string;
  timeoutMs: number;
  rateLimitPerMin: number;
  fallbacks?: LlmFallbackConfig[];
}

export interface LlmHealthStatus {
  configured: boolean;
  healthy: boolean;
  provider?: string;
  lastChecked?: string;
}

export interface AppSettings {
  environmentsEnabled: boolean;
  defaultTheme?: "dark" | "light" | "system";
  agent: AgentSettings;
  deploymentDefaults: DeploymentDefaults;
  envoy: EnvoyEndpointConfig;
  coBranding?: CoBrandingConfig;
  mcpServers?: McpServerConfig[];
  llm?: LlmProviderConfig;
  approvalDefaults?: ApprovalDefaults;
}

export interface CommandInfo {
  version: string;
  host: string;
  port: number;
  startedAt: string;
}

// --- Partition ---

export interface Partition {
  id: string;
  name: string;
  variables: Record<string, string>;
  createdAt: string;
}

// --- Environment ---

export interface Environment {
  id: string;
  name: string;
  variables: Record<string, string>;
}

// --- Artifact ---

export interface ArtifactAnalysis {
  summary: string;
  dependencies: string[];
  configurationExpectations: Record<string, string>;
  deploymentIntent?: string;
  confidence: number;
}

export interface ArtifactAnnotation {
  field: string;
  correction: string;
  annotatedBy: string;
  annotatedAt: string;
}

export interface LearningHistoryEntry {
  timestamp: string;
  event: string;
  details: string;
}

export interface Artifact {
  id: string;
  name: string;
  type: string;
  analysis: ArtifactAnalysis;
  annotations: ArtifactAnnotation[];
  learningHistory: LearningHistoryEntry[];
  /** How this artifact was created — uploaded by a user or generated by an operation */
  source?: { type: "uploaded" | "generated"; operationId?: string };
  createdAt: string;
  updatedAt: string;
}

export interface ArtifactVersion {
  id: string;
  artifactId: string;
  version: string;
  source: string;
  metadata: Record<string, string>;
  createdAt: string;
}

// --- Operation Templates ---

export interface OperationTemplateParam {
  name: string;
  description?: string;
  defaultValue?: string;
}

export interface OperationTemplate {
  id: string;
  name: string;
  description?: string;
  input: OperationInput;
  parameters: OperationTemplateParam[];
  createdAt: string;
  updatedAt: string;
}

// --- Security Boundaries ---

export type SecurityBoundaryType =
  | "filesystem"
  | "service"
  | "network"
  | "credential"
  | "execution";

export interface SecurityBoundary {
  id: string;
  envoyId: string;
  boundaryType: SecurityBoundaryType;
  config: Record<string, unknown>;
}

// --- Deployment ---

export type DeploymentStatus = "pending" | "planning" | "awaiting_approval" | "approved" | "rejected" | "shelved" | "running" | "succeeded" | "failed" | "rolled_back" | "cancelled";

export interface ConfigChange {
  key: string;
  from: string;
  to: string;
}

export interface PlanStep {
  description: string;
  script: string;
  dryRunScript: string | null;
  rollbackScript: string | null;
  reversible: boolean;
}

export interface StepDiff {
  stepIndex: number;
  status: "unchanged" | "changed" | "added" | "removed";
  previous: PlanStep | null;
  current: PlanStep | null;
}

export interface ScriptedPlan {
  platform: "bash" | "powershell";
  reasoning: string;
  steps: PlanStep[];
  diffFromCurrent?: ConfigChange[];
}

export interface DeploymentPlan {
  scriptedPlan: ScriptedPlan;
  reasoning: string;
  diffFromCurrent?: ConfigChange[];
  stepDiffs?: StepDiff[];
}

export interface ExecutionRecord {
  startedAt: string;
  completedAt?: string;
  steps: ExecutedStep[];
}

export interface ExecutedStep {
  description: string;
  status: "completed" | "failed" | "rolled_back";
  startedAt: string;
  completedAt?: string;
  output?: string;
  error?: string;
}

export interface DeploymentEnrichment {
  recentOperationsToEnv: number;
  previouslyRolledBack: boolean;
  conflictingOperations: string[];
  lastOperationToEnv?: {
    id: string;
    status: string;
    version: string;
    completedAt?: string;
  };
}

export interface Deployment {
  id: string;
  artifactId?: string;
  artifactVersionId?: string;
  envoyId?: string;
  partitionId?: string;
  environmentId?: string;
  version: string;
  status: DeploymentStatus;
  variables: Record<string, string>;
  plan?: DeploymentPlan;
  rollbackPlan?: DeploymentPlan;
  executionRecord?: ExecutionRecord;
  approvedBy?: string;
  approvedAt?: string;
  rejectionReason?: string;
  shelvedAt?: string;
  shelvedReason?: string;
  enrichment?: DeploymentEnrichment;
  recommendation?: DeploymentRecommendation;
  /** Discriminated union describing what triggered this operation */
  input?: OperationInput;
  /** Natural language objective */
  intent?: string;
  /** Findings from a query operation */
  queryFindings?: QueryFindings;
  /** Findings from an investigation operation */
  investigationFindings?: InvestigationFindings;
  retryOf?: string;
  /** Who/what initiated this operation */
  triggeredBy?: "user" | "agent" | "webhook" | "trigger";
  /** Trigger-specific fields */
  triggerStatus?: "active" | "paused" | "disabled";
  triggerLastFiredAt?: string;
  triggerFireCount?: number;
  triggerSuppressedCount?: number;
  monitoringDirective?: {
    id: string;
    condition: string;
    responseIntent: string;
    intervalMs: number;
    cooldownMs: number;
    status: "active" | "paused" | "disabled";
  };
  /** Dependencies that must be satisfied before this operation executes */
  waitFor?: WaitCondition[];
  /** Parent operation that spawned this one */
  lineage?: string;
  /** Artifact produced by this operation */
  outputArtifactId?: string;
  debriefEntryIds: string[];
  createdAt: string;
  completedAt: string | null;
  failureReason: string | null;
}

export type RecommendationVerdict = "proceed" | "caution" | "hold";

export interface DeploymentRecommendation {
  verdict: RecommendationVerdict;
  summary: string;
  factors: string[];
}

export interface QueryFindings {
  /** Envoy IDs or hostnames that were probed */
  targetsSurveyed: string[];
  /** LLM narrative summary of what was found */
  summary: string;
  /** Per-target observations */
  findings: Array<{
    target: string;
    observations: string[];
  }>;
}

export interface InvestigationFindings extends QueryFindings {
  rootCause?: string;
  proposedResolution?: {
    intent: string;
    operationType: "maintain" | "deploy";
    parameters?: Record<string, unknown>;
  };
}

export type OperationInput =
  | { type: "deploy"; artifactId: string; artifactVersionId?: string }
  | { type: "maintain"; intent: string; parameters?: Record<string, unknown> }
  | { type: "query"; intent: string }
  | { type: "investigate"; intent: string; allowWrite?: boolean }
  | { type: "execute"; intent: string }
  | { type: "trigger"; condition: string; responseIntent: string; parameters?: Record<string, unknown> }
  | { type: "composite"; steps: CompositeStep[] };

export interface CompositeStep {
  input: OperationInput;
  envoyId?: string;
  waitForSteps?: number[];
  waitFor?: WaitCondition[];
}

export type OperationStatus = "pending" | "planning" | "awaiting_approval" | "approved" | "rejected" | "shelved" | "running" | "succeeded" | "failed" | "rolled_back" | "cancelled";

export interface WaitCondition {
  operationId: string;
  status: OperationStatus;
}

// --- Debrief ---

export type DecisionType =
  | "pipeline-plan"
  | "configuration-resolved"
  | "variable-conflict"
  | "health-check"
  | "deployment-execution"
  | "deployment-verification"
  | "deployment-completion"
  | "deployment-failure"
  | "diagnostic-investigation"
  | "environment-scan"
  | "system"
  | "llm-call"
  | "artifact-analysis"
  | "plan-generation"
  | "plan-approval"
  | "plan-rejection"
  | "rollback-execution"
  | "cross-system-context"
  | "plan-modification"
  | "environment-probe"
  | "pre-flight-llm-failure"
  | "query-findings"
  | "investigation-findings"
  | "trigger-activated"
  | "trigger-fired"
  | "trigger-suppressed"
  | "trigger-paused"
  | "trigger-resumed"
  | "trigger-disabled"
  | "health-report-received";

export type AgentType = "server" | "envoy";

export interface DebriefEntry {
  id: string;
  timestamp: string;
  partitionId: string | null;
  deploymentId: string | null;
  agent: AgentType;
  decisionType: DecisionType;
  decision: string;
  reasoning: string;
  context: Record<string, unknown>;
  actor?: string;
}

// --- Postmortem ---

export interface PostmortemReport {
  summary: string;
  timeline: Array<{
    timestamp: string;
    step: string;
    decision: string;
    reasoning: string;
  }>;
  configuration: {
    variableCount: number;
    conflictCount: number;
    conflicts: Array<{
      description: string;
      riskLevel: string;
      resolution: string;
    }>;
  };
  failureAnalysis: {
    failedStep: string;
    whatHappened: string;
    whyItFailed: string;
    suggestedFix: string;
  } | null;
  outcome: string;
  formatted: string;
}

// --- Identity Provider ---

export type IdpProviderType = "oidc" | "saml" | "ldap";

export interface IdpProvider {
  id: string;
  type: IdpProviderType;
  name: string;
  enabled: boolean;
  config: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface RoleMappingRule {
  id: string;
  providerId: string;
  idpGroup: string;
  synthRole: string;
}

export interface IdpProviderPublic {
  id: string;
  type: IdpProviderType;
  name: string;
}

// --- Artifact Intake ---

export type IntakeChannelType = "webhook" | "registry" | "api" | "manual";

export interface IntakeChannel {
  id: string;
  type: IntakeChannelType;
  name: string;
  enabled: boolean;
  config: Record<string, unknown>;
  authToken?: string;
  lastPolledAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface IntakeEvent {
  id: string;
  channelId: string;
  artifactId?: string;
  status: "received" | "processing" | "completed" | "failed";
  payload: Record<string, unknown>;
  error?: string;
  createdAt: string;
  processedAt?: string;
}
